baseURL: http://example.org/
languageCode: en-us

# dynamic change base on listing name & theme
title: Yellow Tower
theme: Eclectic
author:
  facebook: 'https://facebook.com'
  twitter: 'https://twitter.com'
  email: 'email@contact.page'
  name: 'Yellow Tower'
  location: 'Phnom Penh'
  phone: (015) 325 685
  hours: 'Mon-Fri: 9:00AM - 6:00PM, ET'

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100
    - identifier: contact
      name: Contact
      url: /contact
      weight: 200
params:
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Yellow Tower. All Rights Reserved."
  footer:
    - title: About
      content: >
        Yellow Tower is the world's leading
        manufacturer of digital shapes. From squares and
        circles to triangles and hexagons, we have it
        all. Browse through our collection of various
        forms with different thicknesses and line styles.
        We shape the world. You live in it.

    - title: Recent Blog Posts
      recents: blog
      recentCount: 7

    - title: Contact Us
      contact: true